spring.application.name=applicationLocationVehicule
server.port=9990
spring.jpa.hibernate.ddl=true 
spring.jpa.show-sql=true
spring.datasource.url=jdbc:postgresql://localhost:5432/applicationLocationVehicule
spring.datasource.username=user
spring.datasource.password=passwword